apiVersion: apps/v1
kind: Deployment
metadata:
  name: classrooms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classrooms
  template:
    metadata:
      labels:
        app: classrooms
    spec:
      containers:
      - name: classrooms
        image: abdullaharif1/classrooms-image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: classrooms-service
spec:
  selector:
    app: classrooms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
